### pyrhon zip()


#python map() and filter
numpy
scipy
pandas


In [1]:
import numpy as np
c = np.array([[1, 2, 3],[4,5,6],[7,8,9]])

In [2]:
b=np.array([1,2,3,4,5,6,7,8,9])

In [3]:
b.size

9

In [4]:
c.size

9

In [5]:
c.shape

(3, 3)

In [6]:
np.min(c)

1

In [7]:
np.max(c)

9

In [8]:
np.sum(b)

45

In [9]:
# mean vs median
# 1 5 8 3 4 6 10

# def num_mean():
e = np.array([1,5,8,3,4,6,10])
np.mean(e)


5.285714285714286

In [10]:
np.median(e)

5.0

In [11]:
f = np.array([45,67,89,90,123,456,703,210])
print(np.min(f))
print(np.max(f))
print(np.sum(f))
print(np.mean(f))
print(np.median(f))
f.reshape(2,4)


45
703
1783
222.875
106.5


array([[ 45,  67,  89,  90],
       [123, 456, 703, 210]])

In [12]:
import numpy as np
import scipy

a = np.array([49,56,71,99,53,76,256,12])

In [13]:
a

array([ 49,  56,  71,  99,  53,  76, 256,  12])

In [14]:
#size of array 
a.size

8

In [15]:
a.min()

12

In [16]:
a.max()

256

In [17]:
np.sum(a)

672

In [18]:
np.mean(a)


84.0

In [19]:
np.median(a)

63.5

In [20]:
np.sort(a[::-1])

array([ 12,  49,  53,  56,  71,  76,  99, 256])

In [21]:
np.sort(a)[::-1]

array([256,  99,  76,  71,  56,  53,  49,  12])

In [22]:
b = np.array([49, 76, 71, 99, 53, 76, 256, 259, 12, 49, 222, 49])

In [ ]:
# scipy
from scipy import stats

In [ ]:
d = stats.mode(b)
d

ModeResult(mode=array([49]), count=array([3]))

In [ ]:
d[0]

array([49])

In [ ]:
d[-1]

array([3])

In [ ]:
s = np.arange(51,71) # exclusive
s

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70])

In [ ]:
f = np.reshape(s, (4,5))
f

array([[51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70]])

In [ ]:
len(s)

20

In [ ]:
for i in f:
    # print(i)
    t = np.mean(i)
    print(t)

53.0
58.0
63.0
68.0


In [ ]:
np.sum(f)

1210

In [ ]:
np.sum(f[0])

265

In [ ]:
np.sum(f[1])

290

In [ ]:
np.sum(f[2])

315

In [ ]:
for i in f:
    # print(i)
    t = i[3]
    print(t)

54
59
64
69


In [ ]:
f[0,4]

55

In [ ]:
f[:,3]

array([54, 59, 64, 69])

In [ ]:
f[::,3]

array([54, 59, 64, 69])

In [ ]:
f[:,1]

array([52, 57, 62, 67])

In [ ]:
f[:,3]

array([54, 59, 64, 69])

In [ ]:
f[1:3,2:4]

array([[58, 59],
       [63, 64]])

In [ ]:
f[2:,2:]

array([[63, 64, 65],
       [68, 69, 70]])

In [ ]:
f

array([[51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70]])

In [ ]:
f[:,::2]

array([[51, 53, 55],
       [56, 58, 60],
       [61, 63, 65],
       [66, 68, 70]])

In [ ]:
f[::3,::3]

array([[51, 54],
       [66, 69]])

In [ ]:
x = np.random.randint(200,500,20)
x

array([395, 422, 219, 404, 492, 214, 352, 280, 281, 234, 342, 412, 395,
       344, 280, 301, 387, 202, 302, 421])

In [ ]:
x % 2 == 0

array([False,  True, False,  True,  True,  True,  True,  True, False,
        True,  True,  True, False,  True,  True, False, False,  True,
        True, False])

In [ ]:
x[ x % 2 == 0]

array([422, 404, 492, 214, 352, 280, 234, 342, 412, 344, 280, 202, 302])

In [ ]:
( x % 2 == 0 ) | ( x % 3 == 0 )

array([False,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True, False,  True,  True, False,  True,  True,
        True, False])

In [ ]:
x [ ( x % 2 == 0 ) | ( x % 3 == 0 ) ]

array([422, 219, 404, 492, 214, 352, 280, 234, 342, 412, 344, 280, 387,
       202, 302])

In [ ]:
( x % 2 == 0 ) & ( x % 3 == 0 )

array([False, False, False, False,  True, False, False, False, False,
        True,  True, False, False, False, False, False, False, False,
       False, False])

In [ ]:
x [ ( x % 2 == 0 ) & ( x % 3 == 0 ) ]

array([492, 234, 342])

In [ ]:
np.where( ( x % 2 == 0 ) & ( x % 3 == 0 ) )

(array([ 4,  9, 10]),)

In [ ]:
#1. create boolean array to show value of item that divide by 5 and 3
#2. create boolean array to show value of item that divide by 2 and 7
#3. create boolean array to show value of item that divide by 5 or 7
#4. create boolean array to show value of item that divide by 2 or 3
#5. from  problem 1 to 4 above create boolean indexing of each problem 
#6. from  problem 1 to 4 above find index of each problem item value 
#7. create boolean array that the item has 9 is the last number

In [55]:
b = np.random.randint(100, 1000, 100)
b

array([541, 277, 989, 909, 702, 390, 295, 537, 344, 768, 446, 894, 301,
       388, 828, 637, 854, 828, 211, 838, 461, 870, 471, 997, 251, 655,
       398, 257, 840, 319, 342, 124, 781, 893, 857, 304, 541, 677, 608,
       751, 652, 916, 924, 727, 832, 594, 654, 471, 902, 504, 977, 407,
       873, 303, 578, 625, 859, 257, 654, 655, 998, 339, 396, 972, 162,
       657, 441, 987, 248, 154, 414, 629, 741, 348, 386, 133, 116, 137,
       518, 421, 685, 445, 784, 929, 998, 160, 412, 664, 866, 559, 268,
       893, 469, 569, 444, 425, 400, 291, 761, 468])

In [58]:
c = ( b % 3 == 0 ) & ( b % 5 == 0 )
c

array([False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [ ]:
c = ( b % 3 == 0 ) & ( b % 5 == 0 )
c