In [1]:
import numpy as np

In [ ]:
b = np.random.randint(100, 1000, 100)
b

array([534, 185, 365, 261, 577, 131, 735, 963, 986, 667, 730, 602, 438,
       107, 914, 357, 111, 532, 806, 907, 457, 145, 727, 374, 113, 531,
       144, 829, 230, 189, 280, 432, 330, 800, 843, 797, 675, 676, 967,
       580, 429, 139, 796, 353, 986, 263, 520, 211, 112, 851, 710, 294,
       891, 956, 512, 803, 842, 466, 791, 578, 286, 551, 864, 521, 410,
       715, 318, 397, 492, 399, 296, 297, 650, 518, 875, 671, 211, 961,
       398, 199, 348, 842, 178, 118, 947, 303, 573, 729, 588, 686, 583,
       493, 938, 451, 819, 671, 645, 172, 146, 587])

In [ ]:
#1. create boolean array to show value of item that divide by 5 and 3
#2. create boolean array to show value of item that divide by 2 and 7
#3. create boolean array to show value of item that divide by 5 or 7
#4. create boolean array to show value of item that divide by 2 or 3
#5. from  problem 1 to 4 above create boolean indexing of each problem 
#6. from  problem 1 to 4 above find index of each problem item value 
#7. create boolean array that the item has 9 is the last number
#8. create boolean array sum of each digint equal to 9 or 7

In [ ]:
#1. create boolean array to show value of item that divide by 5 and 3
c_3_and_5 = ( b % 3 == 0 ) & ( b % 5 == 0 )
c_3_and_5

array([False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False])

In [ ]:
#2. create boolean array to show value of item that divide by 2 and 7
c_2_nad_7 = ( b % 2 == 0 ) & ( b % 7 == 0 )
c_2_nad_7

array([False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True,  True,
       False, False,  True, False, False, False, False, False, False,
       False])

In [ ]:
#3. create boolean array to show value of item that divide by 5 or 7
c_5_or_7 = ( b % 5 == 0 ) | ( b % 7 == 0 )
c_5_or_7

array([False,  True,  True, False, False, False,  True, False, False,
       False,  True,  True, False, False, False,  True, False,  True,
       False, False, False,  True, False, False, False, False, False,
       False,  True,  True,  True, False,  True,  True, False, False,
        True, False, False,  True, False, False, False, False, False,
       False,  True, False,  True, False,  True,  True, False, False,
       False, False, False, False,  True, False, False, False, False,
       False,  True,  True, False, False, False,  True, False, False,
        True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True,  True,
       False, False,  True, False,  True, False,  True, False, False,
       False])

In [ ]:
#4. create boolean array to show value of item that divide by 2 or 3
c_2_or_3 = ( b % 2 == 0 ) | ( b % 3 == 0 )
c_2_or_3

array([ True, False, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True, False,  True,  True,  True,  True,
        True, False, False, False, False,  True, False,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True, False,  True,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True,  True,  True,  True,
        True, False,  True,  True, False,  True,  True, False,  True,
       False,  True, False,  True, False,  True,  True,  True,  True,
        True,  True, False, False, False, False,  True, False,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False, False,  True, False,  True, False,  True,  True,  True,
       False])

In [ ]:
#5. from  problem 1 to 4 above create boolean indexing of each problem
print(' _________________________________ divide by 3_and_5 _______________________________________________ \n')
print(b[c_3_and_5])
print(' ___________________________________________________________________________________________________ \n')
print(' _________________________________ divide by 2_nad_7 _______________________________________________ \n')
print(b[c_2_nad_7])
print(' ___________________________________________________________________________________________________ \n')
print(' _________________________________ divide by 5_or_7 _______________________________________________ \n')
print( b[c_5_or_7])
print(' ___________________________________________________________________________________________________ \n')
print(' _________________________________ divide by 2_or_3 _______________________________________________ \n')
print( b[c_2_or_3])
print(' __________________________________________________________________________________________________ \n')


 _________________________________ divide by 3_and_5 _______________________________________________ 

[735 330 675 645]
 ___________________________________________________________________________________________________ 

 _________________________________ divide by 2_nad_7 _______________________________________________ 

[602 532 280 112 294 518 588 686 938]
 ___________________________________________________________________________________________________ 

 _________________________________ divide by 5_or_7 _______________________________________________ 

[185 365 735 730 602 357 532 145 230 189 280 330 800 675 580 520 112 710
 294 791 410 715 399 650 518 875 588 686 938 819 645]
 ___________________________________________________________________________________________________ 

 _________________________________ divide by 2_or_3 _______________________________________________ 

[534 261 735 963 986 730 602 438 914 357 111 532 806 374 531 144 230 189
 280 432 330 800 843 675 

In [ ]:
#6. from  problem 1 to 4 above find index of each problem item value 
print(' _________________________________ divide by 3_and_5 _______________________________________________ \n')
print(np.where( ( b % 3 == 0 ) & ( b % 5 == 0 ) ) )
print(' ___________________________________________________________________________________________________ \n')
print(' _________________________________ divide by 2_nad_7 _______________________________________________ \n')
print(np.where( ( b % 2 == 0 ) & ( b % 7 == 0 ) ) )
print(' ___________________________________________________________________________________________________ \n')
print(' _________________________________ divide by 5_or_7 _______________________________________________ \n')
print( np.where( ( b % 5 == 0 ) | ( b % 7 == 0 ) ) )
print(' ___________________________________________________________________________________________________ \n')
print(' _________________________________ divide by 2_or_3 _______________________________________________ \n')
print( np.where( ( b % 2 == 0 ) | ( b % 3 == 0 ) ) )
print(' ___________________________________________________________________________________________________ \n')


 _________________________________ divide by 3_and_5 _______________________________________________ 

(array([ 6, 32, 36, 96]),)
 ___________________________________________________________________________________________________ 

 _________________________________ divide by 2_nad_7 _______________________________________________ 

(array([11, 17, 30, 48, 51, 73, 88, 89, 92]),)
 ___________________________________________________________________________________________________ 

 _________________________________ divide by 5_or_7 _______________________________________________ 

(array([ 1,  2,  6, 10, 11, 15, 17, 21, 28, 29, 30, 32, 33, 36, 39, 46, 48,
       50, 51, 58, 64, 65, 69, 72, 73, 74, 88, 89, 92, 94, 96]),)
 ___________________________________________________________________________________________________ 

 _________________________________ divide by 2_or_3 _______________________________________________ 

(array([ 0,  3,  6,  7,  8, 10, 11, 12, 14, 15, 16, 17, 18, 23, 2

In [ ]:
#7. create boolean array that the item has 9 is the last number


In [ ]:
print(np.where( l ))

NameError: name 'l' is not defined

In [ ]:
 l = [123,8678,78678]
len(l)
 x[np.where(x)[0][:-2]] = False

TypeError: only integer scalar arrays can be converted to a scalar index