In [2]:
import numpy as np

In [3]:
b = np.random.randint(100, 1000, 100)
b

array([419, 867, 750, 108, 579, 461, 860, 788, 730, 165, 481, 330, 618,
       308, 815, 334, 517, 121, 770, 782, 446, 488, 189, 867, 265, 378,
       900, 846, 614, 759, 318, 715, 629, 783, 228, 281, 787, 232, 299,
       274, 266, 314, 996, 541, 163, 995, 481, 289, 132, 682, 265, 101,
       659, 208, 889, 886, 367, 453, 252, 657, 364, 534, 952, 924, 477,
       803, 968, 501, 203, 920, 341, 226, 862, 764, 656, 701, 425, 955,
       759, 165, 880, 956, 649, 196, 863, 334, 336, 747, 506, 699, 450,
       628, 139, 164, 156, 568, 206, 662, 579, 204])

In [4]:
#1. create boolean array to show value of item that divide by 5 and 3
#2. create boolean array to show value of item that divide by 2 and 7
#3. create boolean array to show value of item that divide by 5 or 7
#4. create boolean array to show value of item that divide by 2 or 3
#5. from  problem 1 to 4 above create boolean indexing of each problem 
#6. from  problem 1 to 4 above find index of each problem item value 
#7. create boolean array that the item has 9 is the last number
#8. create boolean array sum of each digint equal to 9 or 7

In [9]:
#1. create boolean array to show value of item that divide by 5 and 3
c_3_and_5 = ( b % 3 == 0 ) & ( b % 5 == 0 )
c_3_and_5

array([False, False,  True, False, False, False, False, False, False,
        True, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False])

In [10]:
#2. create boolean array to show value of item that divide by 2 and 7
c_2_nad_7 = ( b % 2 == 0 ) & ( b % 7 == 0 )
c_2_nad_7

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
        True, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False,  True, False,  True,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [11]:
#3. create boolean array to show value of item that divide by 5 or 7
c_5_or_7 = ( b % 5 == 0 ) | ( b % 7 == 0 )
c_5_or_7

array([False, False,  True, False, False, False,  True, False,  True,
        True, False,  True, False,  True,  True, False, False, False,
        True, False, False, False,  True, False,  True,  True,  True,
       False, False, False, False,  True, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
        True, False, False, False, False,  True, False, False, False,
        True, False, False, False,  True, False,  True, False,  True,
        True, False, False, False, False,  True,  True, False, False,
       False, False, False, False,  True,  True, False,  True,  True,
       False, False,  True, False, False,  True, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False])

In [12]:
#4. create boolean array to show value of item that divide by 2 or 3
c_2_or_3 = ( b % 2 == 0 ) | ( b % 3 == 0 )
c_2_or_3

array([False,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True,  True, False,  True, False, False,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True, False, False,  True,  True, False,
       False,  True, False,  True,  True,  True,  True, False, False,
       False, False, False,  True,  True, False, False, False,  True,
       False,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True, False,  True, False,  True,
        True,  True,  True, False, False, False,  True,  True,  True,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True])

In [57]:
#5. from  problem 1 to 4 above create boolean indexing of each problem
print(' _________________________________ divide by 3_and_5 _______________________________________________ \n')
print(b[c_3_and_5])
print(' ___________________________________________________________________________________________________ \n')
print(' _________________________________ divide by 2_nad_7 _______________________________________________ \n')
print(b[c_2_nad_7])
print(' ___________________________________________________________________________________________________ \n')
print(' _________________________________ divide by 5_or_7 _______________________________________________ \n')
print( b[c_5_or_7])
print(' ___________________________________________________________________________________________________ \n')
print(' _________________________________ divide by 2_or_3 _______________________________________________ \n')
print( b[c_2_or_3])
print(' __________________________________________________________________________________________________ \n')


 _________________________________ divide by 3_and_5 _______________________________________________ 

[750 165 330 900 165 450]
 ___________________________________________________________________________________________________ 

 _________________________________ divide by 2_nad_7 _______________________________________________ 

[308 770 378 266 252 364 952 924 196 336]
 ___________________________________________________________________________________________________ 

 _________________________________ divide by 5_or_7 _______________________________________________ 

[750 860 730 165 330 308 815 770 189 265 378 900 715 266 995 265 889 252
 364 952 924 203 920 425 955 165 880 196 336 450]
 ___________________________________________________________________________________________________ 

 _________________________________ divide by 2_or_3 _______________________________________________ 

[867 750 108 579 860 788 730 165 330 618 308 334 770 782 446 488 189 867
 378 900 846 614 

In [56]:
#6. from  problem 1 to 4 above find index of each problem item value 
print(' _________________________________ divide by 3_and_5 _______________________________________________ \n')
print(np.where( ( b % 3 == 0 ) & ( b % 5 == 0 ) ) )
print(' ___________________________________________________________________________________________________ \n')
print(' _________________________________ divide by 2_nad_7 _______________________________________________ \n')
print(np.where( ( b % 2 == 0 ) & ( b % 7 == 0 ) ) )
print(' ___________________________________________________________________________________________________ \n')
print(' _________________________________ divide by 5_or_7 _______________________________________________ \n')
print( np.where( ( b % 5 == 0 ) | ( b % 7 == 0 ) ) )
print(' ___________________________________________________________________________________________________ \n')
print(' _________________________________ divide by 2_or_3 _______________________________________________ \n')
print( np.where( ( b % 2 == 0 ) | ( b % 3 == 0 ) ) )
print(' ___________________________________________________________________________________________________ \n')


 _________________________________ divide by 3_and_5 _______________________________________________ 

(array([ 2,  9, 11, 26, 79, 90]),)
 ___________________________________________________________________________________________________ 

 _________________________________ divide by 2_nad_7 _______________________________________________ 

(array([13, 18, 25, 40, 58, 60, 62, 63, 83, 86]),)
 ___________________________________________________________________________________________________ 

 _________________________________ divide by 5_or_7 _______________________________________________ 

(array([ 2,  6,  8,  9, 11, 13, 14, 18, 22, 24, 25, 26, 31, 40, 45, 50, 54,
       58, 60, 62, 63, 68, 69, 76, 77, 79, 80, 83, 86, 90]),)
 ___________________________________________________________________________________________________ 

 _________________________________ divide by 2_or_3 _______________________________________________ 

(array([ 1,  2,  3,  4,  6,  7,  8,  9, 11, 12, 13, 15, 1